### ISSUE TITLE
这次没有之前的BUG 但是现在字符识别出现了问题 \捂脸

### ISSUE THREAD

**Issue by JackyLove01** [voldikss/WechatGameAutoPlayer#30]
数字识别有误差 比如在等号后面的 数字一 经常？识别为数字三
还有就是 运算符 的加减号 识别有误

![TIM截图20190402191449](https://user-images.githubusercontent.com/38373218/55398940-514fca00-557c-11e9-8450-8f10fa311a9e.png)

**Comment by voldikss** [comment]
@JackyLove01 这个只能你自己修改了，我用的识别的方法很不好，当时只是在我个人的电脑上可以用。现在已经不更新了

**Comment by JackyLove01** [comment]
> @JackyLove01 这个只能你自己修改了，我用的识别的方法很不好，当时只是在我个人的电脑上可以用。现在已经不更新了

好的 我想想其他的解决思路

**Comment by voldikss** [comment]
@JackyLove01 另外，你或者可以试试这个 https://github.com/1033020837/WechatGameScript 
它是用逻辑回归做的，识别效果好得多

**Comment by JackyLove01** [comment]
> @JackyLove01 另外，你或者可以试试这个 https://github.com/1033020837/WechatGameScript
> 它是用逻辑回归做的，识别效果好得多

好的 非常感谢
